# PyTorch  
It is a Deep-Learning framework with open source code, which is used to optimize the parameters of computational graphs. 

- Computational Graph - can be any mathematical function or ML model. Often such models are Neural Networks.

### Main properties:  
1. Calculate Gradients in dynamical graphs (structure of model can be changed during training) - allows more variety of options for model creation  
2. Pytorch operates Tensors (torch.Tensor), analogy in Numpy - np.ndarray (objects). Therefore they are similar in functionality - often even name of functions are the same
3. Any model can run on GPU, using small number of lines of code
4. Popular in Industry, convenient in usage for prototyping and deploying models to production

## Examples of usage:

In [4]:
# import
import torch

# create a tensor with shape (3, 2) and random values:
x = torch.randn((3, 2))
x

tensor([[ 0.0021,  0.4230],
        [-0.7158, -0.3617],
        [-2.0795, -0.4164]])

In [5]:
# perform matrix multiplication:
y = torch.mm(x, x.transpose(0, 1))
y

tensor([[ 0.1789, -0.1545, -0.1805],
        [-0.1545,  0.6432,  1.6392],
        [-0.1805,  1.6392,  4.4976]])

In [6]:
# comparison with numpy code:
import numpy as np

# create an array with shape (3, 2) and random values:
x = np.random.randn(3, 2)
x

array([[-0.65597522, -1.55934819],
       [-0.12084307,  1.26710976],
       [ 1.31397273,  0.44220098]])

In [7]:
y = np.dot(x, x.T)
y

array([[ 2.86187029, -1.89659526, -1.55147886],
       [-1.89659526,  1.6201702 ,  0.40153268],
       [-1.55147886,  0.40153268,  1.92206605]])

## Example of Linear regression

In [9]:
# define model:
class LinearRegression(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = torch.nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)
    
# Instantiate the model:
model = LinearRegression()

# Define loss function and optimizer:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Generate some fake data
X = torch.tensor([[1.0], [2.0], [3.0]])
y = torch.tensor([[2.0], [4.0], [6.0]])

for epoch in range(1000):
    # forward pass
    y_pred = model(X)
    loss = criterion(y_pred, y)

    # backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 100 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item()}')

# test the model:
with torch.no_grad():
    y_pred = model(X)
    print(f'Predicted: {y_pred.flatten()}, Ground truth: {y.flatten()}')

Epoch 100, Loss: 8.577387689001625e-07
Epoch 200, Loss: 5.298166456668696e-07
Epoch 300, Loss: 3.279890279372921e-07
Epoch 400, Loss: 2.030388799312277e-07
Epoch 500, Loss: 1.2583990383063792e-07
Epoch 600, Loss: 7.797718382107632e-08
Epoch 700, Loss: 4.823721155844396e-08
Epoch 800, Loss: 3.007428617252117e-08
Epoch 900, Loss: 1.8522408495869058e-08
Epoch 1000, Loss: 1.1542188538271603e-08
Predicted: tensor([1.9998, 4.0000, 6.0001]), Ground truth: tensor([2., 4., 6.])
